name: nim-lang-nightly
summary: Nim programming language, compiler, and other tools.
description: |
  Nim is a compiled, garbage-collected systems programming language with 
  a design that focuses on efficiency, expressiveness, and elegance.
version: 'nightly'
base: core18
grade: devel
confinement: classic

apps:
  nim:
    command: bin/nim
    completer: nim.sh
  nimble:
    command: bin/nimble --nim:$SNAP/bin/nim 
    completer: nimble.sh
  nimcsources:
    command: bin/nim_csources
  nimfind:
    command: bin/nimfind
  nimgrep:
    command: bin/nimgrep
  nimpretty:
    command: bin/nimpretty
  nimsuggest:
    command: bin/nimsuggest
  testament:
    command: bin/testament
  nim-gdb:
    command: bin/nim-gdb.bash    

parts:
  nim-build:
    plugin: dump
    source: https://github.com/nim-lang/Nim.git
    override-build: |
      
      case "$SNAPCRAFT_ARCH_TRIPLET" in
      "x86_64-linux-gnu")
        arch="amd64"
        ;;
      "arm-linux-gnueabihf")
        arch="armhf"
        ;;
      "aarch64-linux-gnu")
        arch="aarch64"
        ;;
      "i386-linux-gnu")
        arch="i386"
        ;;
      "s390x-linux-gnu")
        arch="s390"
        ;;
      "powerpc64le-linux-gnu")
        arch="ppc64el"
        ;;
      *)
        echo "Unsupported architecture $SNAPCRAFT_ARCH_TRIPLET"
        exit 1
        ;;
      esac
      
      sh build_all.sh --os linux --cpu $arch
      bin/nim c koch
      ./koch tools
      rm -v bin/empty.txt
      chmod -v u+x bin/*
      mkdir -v "$SNAPCRAFT_PART_INSTALL"/bin
      mkdir -v "$SNAPCRAFT_PART_INSTALL"/config
      cp -v bin/* "$SNAPCRAFT_PART_INSTALL"/bin
      cp -rv lib/* "$SNAPCRAFT_PART_INSTALL"/lib
      cp -v config/* "$SNAPCRAFT_PART_INSTALL"/config
      cp -v tools/nim.bash-completion "$SNAPCRAFT_PRIME"/nim.sh
      cp -v dist/nimble/nimble.bash-completion "$SNAPCRAFT_PRIME"/nimble.sh
    build-packages:
      - gcc
      - git
    stage-packages:
      - libc6
